### ISSUE TITLE
Make wheels available on PyPI?

### ISSUE THREAD

**Issue by ebogart** [slinderman/pypolyagamma#13]
Would it be possible to make OSX and linux wheels (https://packaging.python.org/distributing/#platform-wheels) for pypolyagamma available on PyPI, to allow users to install the module without requiring compilation from source? 

(If there's no technical reason this won't work, I'd be happy to build the wheel files I want and submit them to you to upload to PyPI, if that's easiest.) 

Thanks!

**Comment by slinderman** [comment]
Hi Eli,
Thanks for the suggestion.  I don't have any experience with wheels but I'm
happy to give it a shot.  What are the cons of this approach?  I guess if I
make future changes to the cython or C code I'll just have to remember to
rebuild the wheels.   I wonder if I compiled with OpenMP support if it
would run on any machine...  Thoughts?

I can build OSX x64 but linux would require some more setup.

Best,
Scott

**Comment by ebogart** [comment]
Hi Scott,

Ah, I didn't think about OpenMP support. I'm new to building wheels myself so I'm not sure what the right approach would be in a case where the extension sometimes needs to be compiled differently. In light of that maybe this isn't a good idea to pursue right now.

Thanks for the reply!
