### ISSUE TITLE
segmentation faults in `pgdrawvpar` when number of threads is not equal to number of cores

### ISSUE THREAD

**Issue by slinderman** [slinderman/pypolyagamma#15]
I tried to run the simple example in the readme on my new machine, which has 12 cores rather than 8.  It seg faulted on the call to `pgdrawvpar`.  Need to fix this.

**Comment by yuanz271** [comment]
Hi Scott. I found that the sample code would work only if `nthreads >= n`.

**Comment by slinderman** [comment]
Thanks. I learned about that a while back and have yet to fix it. I think I will just constrain nthreads to be equal to n cores. Digging into the c code is too time consuming for me right now, but if you want to take a shot by all means go ahead. 

Best,
Scott
