### ISSUE TITLE
Error showing gsl/gsl_rng.h not found when I tried to install on windows 

### ISSUE THREAD

**Issue by yinsenm** [slinderman/pypolyagamma#16]
I tried to install pypolyagamma using pip on a Windows computer with Python 3.6. However, I got the error 

> Cannot open include file: "gsl/gsl_rng.h". 

Then I googled a little bit and found that I need to install the gsl package. I followed the tutorial given by this[ link ](http://joonro.github.io/blog/posts/installing-gsl-and-cythongsl-in-windows.html) and tried again. However, I was still not able to install.

Then I git cloned this repository, tried to install using `python  setup.py install` and I found the setup.py downloads and unzip the latest version of the gsl to deps folder. But I got another error saying that

> Don't know how to compile deps/gsl/gsl_rng.h

I navigated to the deps/gsl folder but there is no gsl_rng.h header file under that folder.  

My questions are the following

1.  How to install pypolyagamma via pip in Windows? How can I add the gsl to the compiler?
2. If pip approach is not available, how can I use `python setup.py install` to install?  Which gsl version was used when this package was written?

Thank you so much for your kind help!

**Comment by slinderman** [comment]
Hi @yinsenm,

Unfortunately I think it will be a challenge to get this to run on Windows given the complexity of getting GSL installed and compiling the code with the GNU compiler.  I'm going to close this as I don't think I'll be able to address this in the near term.  If you are able to work out a way, please let me know and reopen.

Best,
Scott
