### ISSUE TITLE
`nan` when sampling with certain values

### ISSUE THREAD

**Issue by meereeum** [slinderman/pypolyagamma#17]
I'm getting `nan`s for specific parameter settings, that are fixed by specific seemingly arbitrary offsets..

```
pg = pypolyagamma.PyPolyaGamma(seed=47)
n = 10000
x = -211739451879976.94

pg.pgdraw(n, x) # nan

pg.pgdraw(n, x + .01) # nan
pg.pgdraw(n, x + .02) # 2.361392719026314e-11
pg.pgdraw(n, x - .02) # nan
pg.pgdraw(n, x - .05) # 2.3613927190263126e-11

pg.pgdraw(n + 1e-12, x) # 2.361392719026314e-11
pg.pgdraw(n + 4e-12, x) # 2.3613927190263142e-11
pg.pgdraw(n + 5e-12, x) # nan
```

This seems to happen for the same `(n,x)` tuples with both the `pgdraw` and `pgdrawvpar` interfaces, regardless of random seed.

Boundaries might have something to do with machine precision ? But not entirely b/c
```
pg.pgdraw(n, 211739451879976) # nan
pg.pgdraw(n, 211739451879976.1) # 2.361392719026323e-11
```

**Comment by slinderman** [comment]
Hi Miriam,

That seems like a very extreme value of  `x`.  I suspect that it is causing
some numerical issues in the underlying sampling code.  Do you really see
values this extreme in your model?  If so, I would recommend doing some
sort of reparameterization to limit the scale of `x`.  For what it's worth,
I suspect the PG converges to a limiting distribution as `|x| \to \infty`.

Best,
Scott

**Comment by slinderman** [comment]
Hi Miriam,

I'm going to go ahead and close this.  Please reopen if you still are having issues.

Best,
Scott

**Comment by meereeum** [comment]
@slinderman Yep, I encountered this while working with simulated data, but have so far managed to get around it by changing some parameters of the simulation. Will report back if I have more problems. Thank you!

**Comment by zoj613** [comment]
I seem to be having similar issues where the accuracy in my model requires np.float128 / long double precision when doing matrix multiplication with faily small values. It appears that the sampling function `pgprawv` only accepts double/np.float64 types. Any chance that this could be modified to allow the user to selection the precision of the array data type? @slinderman
