### ISSUE TITLE
Error when installing pypolyagamma package 

### ISSUE THREAD

**Issue by sophiabiancalatessa** [slinderman/pypolyagamma#22]
Hello, 

I am having trouble installing the pypolyagamma package in Python. The error message is the following (please view screenshots) 

<img width="741" alt="screen shot 2018-07-07 at 6 47 26 pm" src="https://user-images.githubusercontent.com/40039694/42415280-11ca8f98-8217-11e8-89eb-97f9d1daead4.png">
<img width="743" alt="screen shot 2018-07-07 at 6 47 30 pm" src="https://user-images.githubusercontent.com/40039694/42415281-11ef173c-8217-11e8-9056-d08b8d969a28.png">

Thank you,
Sophia Latessa

**Comment by slinderman** [comment]
Hi Sophia,

Can you try installing from source?  I've just merged a PR (https://github.com/slinderman/pypolyagamma/pull/23) that fixes a broken url in the setup code.  Specifically, can you clone this repo and then run `pip install -e .` from the pypolyagamma directory?

Thanks,
Scott

**Comment by sofiabiancalatessa** [comment]
Dear Mr. Linderman, 

Thank you for your extended advice; I have succeeded in downloading the package. :)

I have a quick question about the input arguments of the resample function: I am inputing # X, an NxD_in array of real-valued inputs and my output is # Y, and NxD_out array of binary observations (D_in = 2 while D_out = 1 and n = 1000). I am having a joint error message; is this error message common?

I really appreciate your time and advice—it is very helpful for my research. 

Thank you again.

Best wishes,
Sophia Latessa

**Comment by srbittner** [comment]
Hi Scott,

I'm using python 3.6 in an environment with pylds (except pypolyagamma) and its dependencies installed.  I git cloned the repo, and ran `pip install -e .` as you suggested.  I'm running into the following test failure:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/sbittner/Documents/rand_tensor/lib/pypolyagamma/setup.py", line 55, in <module>
        assert os.path.exists(os.path.join("pypolyagamma", "pypolyagamma.cpp"))
    AssertionError
```

Do you know what's going on here?

Best,
Sean

**Comment by slinderman** [comment]
Thanks, Sean.  After our discussion last week, I added a more informative error message and a line to the README saying to install cython first.

https://github.com/slinderman/pypolyagamma/commit/f8c81a5bd7f93aa99083050a34af4b65fcd31d5b
