### ISSUE TITLE
Import error: undefined symbol

### ISSUE THREAD

**Issue by kekehia123** [slinderman/pypolyagamma#24]
When I import pypolyagamma, I got an error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-678fdb3a5c81> in <module>()
----> 1 import pypolyagamma

/data/home/sxk/Documents/eeg_anal/pypolyagamma/pypolyagamma/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 from warnings import warn
----> 3 from pypolyagamma.pypolyagamma import PyRNG, PyPolyaGamma
      4 
      5 # Try to import the parallel version, but if they didn't compile,

ImportError: /data/home/sxk/Documents/eeg_anal/pypolyagamma/pypolyagamma/pypolyagamma.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

I installed pypolyagamma via downloading the package and ran "pip install -e pypolyagamma".
I'm using python 3.5.4 in Anaconda.

Thanks in advance!

**Comment by slinderman** [comment]
Hi @kekehia123, it shouldn't matter if you download the zip or git clone it.   Did you follow the Manual Instructions in the README and run `pip install -e .`?


(The clone error looks like perhaps a problem with your SSH key. You could check out https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/.)
