### ISSUE TITLE
include LICENSE file

### ISSUE THREAD

**Issue by beckermr** [slinderman/pypolyagamma#28]
I just noticed that this repo doesn't have a license file. The feedstock says MIT. A license file with the MIT license should be added to the repo. You should also add it to the MANIFEST.in

**Comment by beckermr** [comment]
Also thanks for the other fixes @slinderman!

**Comment by slinderman** [comment]
License added and version revved. https://github.com/slinderman/pypolyagamma/commit/753759cd54c1271dd8b92e0380aeb4fb22094e55 

Note: I went with GNU GPL v3 to be consistent with BayesLogit package, which is redistributed in pypolyagamma.

**Comment by beckermr** [comment]
Ahhh then we need to change the conda-forge package which says MIT.

**Comment by slinderman** [comment]
Sorry, I don't think there's any way around this.  Hopefully it's not a big change on the conda-forge side.

**Comment by beckermr** [comment]
Not a problem at all! :)
