### ISSUE TITLE
`logsumexp` not available due to Scipy version

### ISSUE THREAD

**Issue by gwgundersen** [slinderman/pypolyagamma#35]
I created a Python 3.7 conda environment and followed the "Manual installation" instructions. However, I got error because Python could not import `logsumexp` from `scipy.misc`. The function is in `scipy.special` in the latest version of `scipy`. I am happy to create a PR to address this issue if you can suggest a way forward. My thoughts are:

1. I did something wrong and can close this issue.
2. I can amend the docs to clarify which versions of Python and Scipy are supported.
3. I can (try to) add support for Python 3.7 + Scipy 1.3.

**Comment by slinderman** [comment]
Hi, please see if this PR https://github.com/slinderman/pypolyagamma/pull/34 fixes this issue for you. I just merged it into master.

**Comment by gwgundersen** [comment]
Yes, that resolved it. Thanks!
