### ISSUE TITLE
ImportError: cannot import name 'logsumexp'

### ISSUE THREAD

**Issue by olivierjeunen** [slinderman/pypolyagamma#37]
I installed the library using pip, with scipy verison 1.3.1.
When I try to import ```pypolyagamma```, I get the following error:

```
>>> import pypolyagamma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/pypolyagamma/__init__.py", line 23, in <module>
    from pypolyagamma.distributions import BernoulliRegression, \
  File ".../lib/python3.6/site-packages/pypolyagamma/distributions.py", line 6, in <module>
    from scipy.misc import logsumexp
ImportError: cannot import name 'logsumexp'
```

The reason for this is that the ```logsumexp``` function moved from ```scipy.misc``` to ```scipy.special``` in recent versions of scipy. Changing the import statement to reflect this should fix the issue.
(Or alternatively, downgrading scipy as a temporary workaround)

**Comment by zoj613** [comment]
@slinderman ping

**Comment by slinderman** [comment]
Fixed in the latest release.
