### ISSUE TITLE
cut a new release

### ISSUE THREAD

**Issue by beckermr** [slinderman/pypolyagamma#38]
The scipy compatibility fix for using logsumexp is on master but not in a released version. A release is needed to build the conda-forge package. Can we cut a new version?

@slinderman for viz

conda-forge xref: https://github.com/conda-forge/pypolyagamma-feedstock/pull/11

**Comment by macks22** [comment]
@slinderman any update on this? Ran into this scipy compatibility issue today and had to choose between downgrading scipy version or using a from-source install, which always makes me uneasy. Would be great to get this available as an official release!

**Comment by slinderman** [comment]
I updated the version number in `setup.py` and created a new release here: https://github.com/slinderman/pypolyagamma/tree/1.2.3 

Not entirely sure that this is what you were requesting, so please let me know if more changes are necessary!  

Apologies for the very long delay.

**Comment by beckermr** [comment]
thank you!

**Comment by beckermr** [comment]
this worked and the new version should be on conda-forge within and hour or so. closing!
