### ISSUE TITLE
installation on unix systems fails due to strange shutil.move behavior

### ISSUE THREAD

**Issue by slinderman** [slinderman/pypolyagamma#4]
Looks like the attempt to move `deps/gsl-2.2.1` to `deps/gsl` is not working properly on linux. It seems to be creating a regular file named `deps/gsl` rather than copying the directory.

**Comment by Spaak** [comment]
I seem to be suffering from this issue (see below). Any workarounds?

```
(newanalysis) eelke@eelkebox:~/repos/pypolyagamma$ USE_OPENMP=True pip install -e .
Obtaining file:///home/eelke/repos/pypolyagamma
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/eelke/repos/pypolyagamma/setup.py", line 55, in <module>
        subprocess.call("./configure", cwd=gslpath, shell=True)
      File "/usr/local/lib/python3.4/subprocess.py", line 537, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/local/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.4/subprocess.py", line 1463, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    NotADirectoryError: [Errno 20] Not a directory


```

**Comment by Spaak** [comment]
In case anyone else finds this issue, a simple workaround is to run `pip install -e .` once, it will download GSL and then fail. Then, go into the `deps/` folder,  `rm gsl` and `mv gsl-2.3 gsl` (change to the version number it downloaded) and `cd gsl` and `./configure`. After that, runing `pip install -e .` from the original folder will work.

**Comment by slinderman** [comment]
Thanks for the workaround!  The build script takes an (admittedly hacky) approach of downloading GSL and configuring it to get the necessary headers.  I only do that in order to make it easier for Mac OSX users who often have trouble installing GSL.  I'll see if I can figure out the regular file issue on Unix so that this works.

**Comment by slinderman** [comment]
I just realized that I accidentally deleted the `deps` directory with my most recent change. I've added it back and made sure that it is included in the pypi manifest.  See https://github.com/slinderman/pypolyagamma/commit/e06dea3bfba44497881b506731a28854c19d7261.  Please reopen this issue if your problem has not been solved.

**Comment by eterna2** [comment]
Gotten this error
```
NotADirectoryError: [Errno 20] Not a directory: 'deps/gsl-latest.tar.gz'

```

Dun think u manage to put `deps` back.

**Comment by slinderman** [comment]
@eterna2 this looks like something different -- seems like it expected the .tar.gz file to be a directory. Can you provide some more context. Did you install from `pip` or by cloning the repo and running `python setup.py install`? Were there other messages printed before this error?
