### ISSUE TITLE
Issues with installing pypolyagamma

### ISSUE THREAD

**Issue by satukikalverda** [slinderman/pypolyagamma#40]
Hi there,

I would like to make use of the pypolyagamma sample generator, however i have some trouble installing it and dont really know how to fix it. I was wondering if you could take a look. The following error is what i get.

(base) C:\Users\SatukiKalverda\PythonScripts\pypolyagamma-master>python setup.py
Downloading GSL...
Extracting to deps\gsl
...Done!
'.' is not recognized as an internal or external command,
operable program or batch file.
'make' is not recognized as an internal or external command,
operable program or batch file.
Compiling pypolyagamma/pypolyagamma.pyx because it changed.
[1/1] Cythonizing pypolyagamma/pypolyagamma.pyx
C:\Users\SatukiKalverda\Anaconda3\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\SatukiKalverda\PythonScripts\pypolyagamma-master\pypolyagamma\pypolyagamma.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
C:\Users\SatukiKalverda\Anaconda3\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by macks22** [comment]
@satukikalverda looks like you just need to call `python setup.py` with the `install` command. Did you try this?
```
python setup.py install
```

**Comment by satukikalverda** [comment]
Hi Macks22,

Thanks for your reply. I have tried your suggestion, however I'm not still able to install the package. When I run the command  `python setup.py install`, I get the following message. 

```
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c deps/gsl/rng/mt.c -o build\temp.win-amd64-3.7\Release\deps\gsl\rng\mt.o -w -DHAVE_INLINE
deps/gsl/rng/mt.c:54:20: fatal error: config.h: No such file or directory
compilation terminated.
error: command 'C:\\Users\\SatukiKalverda\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
```
I dont really know how to fix the above problem. :/

**Comment by macks22** [comment]
Hmm... That config.h file comes from configuring GSL, which is normally done by the setup.py. You might try removing the entire deps/gsl folder, then running `python setup.py egg_info`, then looking for `deps/gsl/config.h`. If that's present, you shouldn't get the error again. If it's not, it's probably because something failed during the configuration, so you can look back in the logs for that to see what's going wrong.

**Comment by satukikalverda** [comment]
Hi there Macks22,

I have tried your suggestion, and the file `deps/gsl/config.h` is still not there.  If I look into the log; 

`(base) C:\Users\SatukiKalverda\PythonScripts\pypolyagamma-master>python setup.py install
'.' is not recognized as an internal or external command,
operable program or batch file.
'make' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\SatukiKalverda\Anaconda3\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing pypolyagamma.egg-info\PKG-INFO
writing dependency_links to pypolyagamma.egg-info\dependency_links.txt
writing requirements to pypolyagamma.egg-info\requires.txt
writing top-level names to pypolyagamma.egg-info\top_level.txt
reading manifest file 'pypolyagamma.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'pypolyagamma.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pypolyagamma.pypolyagamma' extension
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/pypolyagamma.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\pypolyagamma.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/PolyaGamma.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\polyagamma.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/PolyaGammaSmallB.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\polyagammasmallb.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/PolyaGammaAlt.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\polyagammaalt.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/PolyaGammaSP.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\polyagammasp.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/InvertY.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\inverty.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/include/RNG.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\include\rng.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c pypolyagamma/cpp/include/GRNG.cpp -o build\temp.win-amd64-3.7\Release\pypolyagamma\cpp\include\grng.o -w -DHAVE_INLINE
C:\Users\SatukiKalverda\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -IC:\Users\SatukiKalverda\Anaconda3\include -IC:\Users\SatukiKalverda\Anaconda3\include -c deps/gsl/rng/mt.c -o build\temp.win-amd64-3.7\Release\deps\gsl\rng\mt.o -w -DHAVE_INLINE
deps/gsl/rng/mt.c:54:20: fatal error: config.h: No such file or directory
compilation terminated.
error: command 'C:\\Users\\SatukiKalverda\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1`

I suspect that it has to do with the follwing lines:

`warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution`

However, Im not competent enough to fix the problem. Do you have any suggestion to overcome this problem?

Thank you very much for your suggestion!

**Comment by macks22** [comment]
I think the problem is the first line. Do you have `make` installed and accessible in the shell? It looks like that may be the issue. 

I'm not as familiar with Windows, but a first step would be to make sure you've added the anaconda install you're using to the system path. Normally, you'd do this when you install anaconda. If you didn't, you can follow the instructions here: https://stackoverflow.com/q/49616399/2486302. You may need to restart your shell for changes to take effect. You can verify your install is setup correctly following the instructions here: https://docs.anaconda.com/anaconda/install/verify-install/

If that is verified and the problem is not resolved... If you have a bash shell, can you run the following and include the full output? If you are using something other than bash, you may need to follow some custom instructions for getting the C++ compiler installed and linked to the python install commands, [e.g. for mingw](https://stackoverflow.com/q/3297254/2486302).

```
python --version
which pip
conda install libgcc
pip install -U pip setuptools cython
find . -print
python setup.py egg_info
ls deps/gsl | grep config
```

**Comment by slinderman** [comment]
@satukikalverda: Sorry but I've never tried installing this on Windows.  Perhaps the easiest approach is to fire up a Linux VM?
