### ISSUE TITLE
Issues with installing pypolyagamma on win64

### ISSUE THREAD

**Issue by z5041294** [slinderman/pypolyagamma#42]
Hi,

I have some trouble to install this package on win64 system. I don't know how to fix it. I hope you can give me some help. 

Many thanks
Xiongwen

(base) PS C:\Users\KE XIONGWEN> pip install git+git://github.com/slinderman/pypolyagamma.git
Collecting git+git://github.com/slinderman/pypolyagamma.git
  Cloning git://github.com/slinderman/pypolyagamma.git to c:\users\kexion~1\appdata\local\temp\pip-req-build-vcn1q57g
  Running command git clone -q git://github.com/slinderman/pypolyagamma.git 'C:\Users\KEXION~1\AppData\Local\Temp\pip-req-build-vcn1q57g'
  fatal: cannot create directory at 'aux': Invalid argument
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

ERROR: Command errored out with exit status 128: git clone -q git://github.com/slinderman/pypolyagamma.git 'C:\Users\KEXION~1\AppData\Local\Temp\pip-req-build-vcn1q57g' Check the logs for full command output.

**Comment by slinderman** [comment]
Hmm, installation are difficult since they are so system specific. I don't have any experience installing on Windows. I was able to install from source (see README.md) on Big Sur 11.1 with (Anaconda) Python 3.7.7.
