### ISSUE TITLE
failed to install pypolyagamma

### ISSUE THREAD

**Issue by kiiiwi** [slinderman/pypolyagamma#43]
Hi,

I would like to run the example of recurrent-slds, but met with some problems when installing the 'pypolyagamma'. Hope to get some suggestions from you.

I installed pypolyagamma through 'pip', but got the errors as follows:

 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -ID:\anaconda3\include -ID:\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppypolyagamma/pypolyagamma.cpp /Fobuild\temp.win-amd64-3.7\Release\pypolyagamma/pypolyagamma.obj -w -DHAVE_INLINE
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    pypolyagamma.cpp
    c:\users\natalie\appdata\local\temp\pip-install-vzx83du8\pypolyagamma\pypolyagamma\cpp\include\GRNG.hpp(32): fatal error C1083: Cannot open include file: 'gsl/gsl_rng.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\natalie\\AppData\\Local\\Temp\\pip-install-vzx83du8\\pypolyagamma\\setup.py'"'"'; __file__='"'"'C:\\Users\\natalie\\AppData\\Local\\Temp\\pip-install-vzx83du8\\pypolyagamma\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\natalie\AppData\Local\Temp\pip-record-hzyx8eb2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\anaconda3\Include\pypolyagamma' Check the logs for full command output.

Besides, when i run the 'from pypolyagamma.binary_trees import balanced_binary_tree', which is the code from tree-rslds.py, the report error is :
ModuleNotFoundError: No module named 'pypolyagamma.pypolyagamma'.

**Comment by slinderman** [comment]
Looks like there was a problem downloading GSL. I just tried a fresh install (from source, see README) on Big Sur (11.1) and Anaconda Python 3.7.7 and it worked fine. Perhaps try upgrading and installing from source?
