### ISSUE TITLE
version 1.2.3 not available on PyPi

### ISSUE THREAD

**Issue by zoj613** [slinderman/pypolyagamma#44]
it seems as though a release of 1.2.3 has been made but it is not uploaded on PyPi. This version is important as it allows import of expit from scipy.special instead of scipy.misc. I cant use PyPolyagamma now that I have upgraded to scipy 1.5.

**Comment by slinderman** [comment]
Thanks for the reminder. Just uploaded to [PyPI](https://pypi.org/project/pypolyagamma/1.2.3/).  Please see if this works for you.

**Comment by zoj613** [comment]
It installs now, thanks.
