### ISSUE TITLE
error in installation in Windows

### ISSUE THREAD

**Issue by mushtaqpatel0505** [slinderman/pypolyagamma#46]
Building wheel for pypolyagamma (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Mushtaq\anaconda3\envs\ml\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mushtaq\\AppData\\Local\\Temp\\pip-install-xxf_1yl8\\pypolyagamma\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mushtaq\\AppData\\Local\\Temp\\pip-install-xxf_1yl8\\pypolyagamma\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Mushtaq\AppData\Local\Temp\pip-wheel-rfn27xmg'
       cwd: C:\Users\Mushtaq\AppData\Local\Temp\pip-install-xxf_1yl8\pypolyagamma\
  Complete output (19 lines):
  '.' is not recognized as an internal or external command,
  operable program or batch file.
  'make' is not recognized as an internal or external command,
  operable program or batch file.
  C:\Users\Mushtaq\anaconda3\envs\ml\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pypolyagamma
  copying pypolyagamma\binary_trees.py -> build\lib.win-amd64-3.7\pypolyagamma
  copying pypolyagamma\distributions.py -> build\lib.win-amd64-3.7\pypolyagamma
  copying pypolyagamma\utils.py -> build\lib.win-amd64-3.7\pypolyagamma
  copying pypolyagamma\__init__.py -> build\lib.win-amd64-3.7\pypolyagamma
  running build_ext
  building 'pypolyagamma.pypolyagamma' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pypolyagamma
  Running setup.py clean for pypolyagamma
Failed to build pypolyagamma
Installing collected packages: pypolyagamma
    Running setup.py install for pypolyagamma ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Mushtaq\anaconda3\envs\ml\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mushtaq\\AppData\\Local\\Temp\\pip-install-xxf_1yl8\\pypolyagamma\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mushtaq\\AppData\\Local\\Temp\\pip-install-xxf_1yl8\\pypolyagamma\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mushtaq\AppData\Local\Temp\pip-record-k7sjk1h6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Mushtaq\anaconda3\envs\ml\Include\pypolyagamma'
         cwd: C:\Users\Mushtaq\AppData\Local\Temp\pip-install-xxf_1yl8\pypolyagamma\
    Complete output (19 lines):
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    'make' is not recognized as an internal or external command,
    operable program or batch file.
    C:\Users\Mushtaq\anaconda3\envs\ml\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pypolyagamma
    copying pypolyagamma\binary_trees.py -> build\lib.win-amd64-3.7\pypolyagamma
    copying pypolyagamma\distributions.py -> build\lib.win-amd64-3.7\pypolyagamma
    copying pypolyagamma\utils.py -> build\lib.win-amd64-3.7\pypolyagamma
    copying pypolyagamma\__init__.py -> build\lib.win-amd64-3.7\pypolyagamma
    running build_ext
    building 'pypolyagamma.pypolyagamma' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Mushtaq\anaconda3\envs\ml\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mushtaq\\AppData\\Local\\Temp\\pip-install-xxf_1yl8\\pypolyagamma\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mushtaq\\AppData\\Local\\Temp\\pip-install-xxf_1yl8\\pypolyagamma\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mushtaq\AppData\Local\Temp\pip-record-k7sjk1h6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Mushtaq\anaconda3\envs\ml\Include\pypolyagamma' Check the logs for full command output.

**Comment by slinderman** [comment]
Hmm, looks like you need to install the VS build tools. I don't have any experience building on Windows, and unfortunately I'm unable to support build issues as they are fairly system specific.
