### ISSUE TITLE
Error in import pypolyagaamma

### ISSUE THREAD

**Issue by Dawei-Ding** [slinderman/pypolyagamma#47]
Mac OS 10.15.7
Python version 3.7.4

import pypolyagamma

ImportError: dlopen(/Users/david/opt/anaconda3/lib/python3.7/site-packages/pypolyagamma/pypolyagamma.cpython-37m-darwin.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: /Users/david/opt/anaconda3/lib/python3.7/site-packages/pypolyagamma/pypolyagamma.cpython-37m-darwin.so
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/david/opt/anaconda3/lib/python3.7/site-packages/pypolyagamma/pypolyagamma.cpython-37m-darwin.so

**Comment by slinderman** [comment]
Looks like a linking issue... these are difficult to debug unfortunately. I was able to install from source (see README.md) on Big Sur 11.1 with (Anaconda) Python 3.7.7.
