### ISSUE TITLE
ImportError with python 2

### ISSUE THREAD

**Issue by nfoti** [slinderman/pypolyagamma#5]
When I try importing `pypolyagamma` from python 2.7 I get an `ImportError` complaining that there is no module `utils` from the distributions.py` file. However, the package works fine with python 3.6. Maybe a problem with a missing `absolute_import`?

I'm using `pypolyagamma-1.1` installed via pip from `pyslds` if that helps.

Thanks.

**Comment by nfoti** [comment]
This issue seems to be fixed if I use the `master` branch of `pypolyagamma` rather than the one grabbed from `pip`. So maybe the version on pypi just needs to be updated.

**Comment by slinderman** [comment]
Thanks Nick. I'm away on vacation for a couple weeks. I'll get to this as soon as I'm back.
Best,
Scott

**Comment by damely** [comment]
Hey there -- minor thing: installing from a clone of the repo (`pip install -e pypolyagamma`) will fail if the empty folder `pypolyagamma/deps` is not created beforehand.
Thanks for the great work!

**Comment by slinderman** [comment]
@nfoti @damely -- I'm obviously a bit late on this, but master and pypi should now be synced up. I'm going to go ahead and close this.
