### ISSUE TITLE
Failed to install on cluster under miniconda virtue env

### ISSUE THREAD

**Issue by hurazh** [slinderman/pypolyagamma#50]
All requirement is satisfied. Both pip and manual installation raised the same error message
OS: CentOS 7
GCC version: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

I was able to install it successfully on Big Sur (11.2.3) with anaconda and another Ubuntu cluster (18.04.5 LTS).
The error message is pretty long. It begins with 
```
Installing collected packages: pypolyagamma
  Running setup.py develop for pypolyagamma
    ERROR: Command errored out with exit status 1:
     command: /home/zhangh9/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"'; __file__='"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /juno/home/zhangh9/st/pypolyagamma/
    Complete output (2203 lines):
    running develop
    running egg_info
    writing pypolyagamma.egg-info/PKG-INFO
    writing dependency_links to pypolyagamma.egg-info/dependency_links.txt
    writing requirements to pypolyagamma.egg-info/requires.txt
    writing top-level names to pypolyagamma.egg-info/top_level.txt
    reading manifest file 'pypolyagamma.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /home/zhangh9/miniconda3/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
      warnings.warn(msg)
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'pypolyagamma.egg-info/SOURCES.txt'
    running build_ext
    building 'pypolyagamma.pypolyagamma' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/pypolyagamma
    creating build/temp.linux-x86_64-3.8/pypolyagamma/cpp
    creating build/temp.linux-x86_64-3.8/pypolyagamma/cpp/include
    creating build/temp.linux-x86_64-3.8/deps
    creating build/temp.linux-x86_64-3.8/deps/gsl
    creating build/temp.linux-x86_64-3.8/deps/gsl/rng
    creating build/temp.linux-x86_64-3.8/deps/gsl/cdf
    creating build/temp.linux-x86_64-3.8/deps/gsl/randist
    creating build/temp.linux-x86_64-3.8/deps/gsl/err
    creating build/temp.linux-x86_64-3.8/deps/gsl/specfunc
    creating build/temp.linux-x86_64-3.8/deps/gsl/complex
    creating build/temp.linux-x86_64-3.8/deps/gsl/sys
```
following hundreds of lines of warnings about `-Wstrict-prototypes`, like
```
gcc -pthread -B /home/zhangh9/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -I/home/zhangh9/miniconda3/include/python3.8 -c pypolyagamma/pypolyagamma.cpp -o build/temp.linux-x86_64-3.8/pypolyagamma/pypolyagamma.o -w -DHAVE_INLINE
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -B /home/zhangh9/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -I/home/zhangh9/miniconda3/include/python3.8 -c pypolyagamma/cpp/PolyaGamma.cpp -o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGamma.o -w -DHAVE_INLINE
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
``` 
and thousands of lines of multiple definition errors like
```
g++ -pthread -shared -B /home/zhangh9/miniconda3/compiler_compat -L/home/zhangh9/miniconda3/lib -Wl,-rpath=/home/zhangh9/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/pypolyagamma/pypolyagamma.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGamma.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGammaSmallB.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGammaAlt.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGammaSP.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/InvertY.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/include/RNG.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/include/GRNG.o build/temp.linux-x86_64-3.8/deps/gsl/rng/mt.o build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o build/temp.linux-x86_64-3.8/deps/gsl/randist/bernoulli.o build/temp.linux-x86_64-3.8/deps/gsl/randist/beta.o build/temp.linux-x86_64-3.8/deps/gsl/randist/chisq.o build/temp.linux-x86_64-3.8/deps/gsl/randist/exponential.o build/temp.linux-x86_64-3.8/deps/gsl/randist/flat.o build/temp.linux-x86_64-3.8/deps/gsl/randist/gamma.o build/temp.linux-x86_64-3.8/deps/gsl/randist/gauss.o build/temp.linux-x86_64-3.8/deps/gsl/randist/gausszig.o build/temp.linux-x86_64-3.8/deps/gsl/rng/rng.o build/temp.linux-x86_64-3.8/deps/gsl/err/error.o build/temp.linux-x86_64-3.8/deps/gsl/rng/file.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/gamma.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/gamma_inc.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/erfc.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/exp.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/expint.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/trig.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/log.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/psi.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/zeta.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/elementary.o build/temp.linux-x86_64-3.8/deps/gsl/complex/math.o build/temp.linux-x86_64-3.8/deps/gsl/sys/infnan.o build/temp.linux-x86_64-3.8/deps/gsl/sys/fdiv.o build/temp.linux-x86_64-3.8/deps/gsl/sys/coerce.o build/temp.linux-x86_64-3.8/deps/gsl/err/stream.o -o build/lib.linux-x86_64-3.8/pypolyagamma/pypolyagamma.cpython-38-x86_64-linux-gnu.so
    /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_2':
    /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:46: multiple definition of `gsl_pow_2'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:46: first defined here
    /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_3':
    /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:47: multiple definition of `gsl_pow_3'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:47: first defined here
    /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_4':
    /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:48: multiple definition of `gsl_pow_4'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:48: first defined here
    /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_5':
    /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:49: multiple definition of `gsl_pow_5'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:49: first defined here
``` 
ending with 
```
/home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/complex/math.o: in function `gsl_complex_rect':
    /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_complex_math.h:50: multiple definition of `gsl_complex_rect'; build/temp.linux-x86_64-3.8/deps/gsl/specfunc/psi.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_complex_math.h:50: first defined here
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zhangh9/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"'; __file__='"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
We tried to change the `gslurl` in `setup.py` as mentioned in #18 but it didn't work either.

**Comment by PanBikang** [comment]
> All requirement is satisfied. Both pip and manual installation raised the same error message OS: CentOS 7 GCC version: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
> 
> I was able to install it successfully on Big Sur (11.2.3) with anaconda and another Ubuntu cluster (18.04.5 LTS). The error message is pretty long. It begins with
> 
> ```
> Installing collected packages: pypolyagamma
>   Running setup.py develop for pypolyagamma
>     ERROR: Command errored out with exit status 1:
>      command: /home/zhangh9/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"'; __file__='"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
>          cwd: /juno/home/zhangh9/st/pypolyagamma/
>     Complete output (2203 lines):
>     running develop
>     running egg_info
>     writing pypolyagamma.egg-info/PKG-INFO
>     writing dependency_links to pypolyagamma.egg-info/dependency_links.txt
>     writing requirements to pypolyagamma.egg-info/requires.txt
>     writing top-level names to pypolyagamma.egg-info/top_level.txt
>     reading manifest file 'pypolyagamma.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     /home/zhangh9/miniconda3/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
>       warnings.warn(msg)
>     warning: no previously-included files matching '*.pyc' found anywhere in distribution
>     warning: no previously-included files matching '*.pyo' found anywhere in distribution
>     warning: no previously-included files matching '*.so' found anywhere in distribution
>     writing manifest file 'pypolyagamma.egg-info/SOURCES.txt'
>     running build_ext
>     building 'pypolyagamma.pypolyagamma' extension
>     creating build/temp.linux-x86_64-3.8
>     creating build/temp.linux-x86_64-3.8/pypolyagamma
>     creating build/temp.linux-x86_64-3.8/pypolyagamma/cpp
>     creating build/temp.linux-x86_64-3.8/pypolyagamma/cpp/include
>     creating build/temp.linux-x86_64-3.8/deps
>     creating build/temp.linux-x86_64-3.8/deps/gsl
>     creating build/temp.linux-x86_64-3.8/deps/gsl/rng
>     creating build/temp.linux-x86_64-3.8/deps/gsl/cdf
>     creating build/temp.linux-x86_64-3.8/deps/gsl/randist
>     creating build/temp.linux-x86_64-3.8/deps/gsl/err
>     creating build/temp.linux-x86_64-3.8/deps/gsl/specfunc
>     creating build/temp.linux-x86_64-3.8/deps/gsl/complex
>     creating build/temp.linux-x86_64-3.8/deps/gsl/sys
> ```
> 
> following hundreds of lines of warnings about `-Wstrict-prototypes`, like
> 
> ```
> gcc -pthread -B /home/zhangh9/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -I/home/zhangh9/miniconda3/include/python3.8 -c pypolyagamma/pypolyagamma.cpp -o build/temp.linux-x86_64-3.8/pypolyagamma/pypolyagamma.o -w -DHAVE_INLINE
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
>     gcc -pthread -B /home/zhangh9/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipypolyagamma -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/gsl/gsl -I/home/zhangh9/miniconda3/include/python3.8 -c pypolyagamma/cpp/PolyaGamma.cpp -o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGamma.o -w -DHAVE_INLINE
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
> ```
> 
> and thousands of lines of multiple definition errors like
> 
> ```
> g++ -pthread -shared -B /home/zhangh9/miniconda3/compiler_compat -L/home/zhangh9/miniconda3/lib -Wl,-rpath=/home/zhangh9/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/pypolyagamma/pypolyagamma.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGamma.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGammaSmallB.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGammaAlt.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/PolyaGammaSP.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/InvertY.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/include/RNG.o build/temp.linux-x86_64-3.8/pypolyagamma/cpp/include/GRNG.o build/temp.linux-x86_64-3.8/deps/gsl/rng/mt.o build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o build/temp.linux-x86_64-3.8/deps/gsl/randist/bernoulli.o build/temp.linux-x86_64-3.8/deps/gsl/randist/beta.o build/temp.linux-x86_64-3.8/deps/gsl/randist/chisq.o build/temp.linux-x86_64-3.8/deps/gsl/randist/exponential.o build/temp.linux-x86_64-3.8/deps/gsl/randist/flat.o build/temp.linux-x86_64-3.8/deps/gsl/randist/gamma.o build/temp.linux-x86_64-3.8/deps/gsl/randist/gauss.o build/temp.linux-x86_64-3.8/deps/gsl/randist/gausszig.o build/temp.linux-x86_64-3.8/deps/gsl/rng/rng.o build/temp.linux-x86_64-3.8/deps/gsl/err/error.o build/temp.linux-x86_64-3.8/deps/gsl/rng/file.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/gamma.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/gamma_inc.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/erfc.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/exp.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/expint.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/trig.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/log.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/psi.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/zeta.o build/temp.linux-x86_64-3.8/deps/gsl/specfunc/elementary.o build/temp.linux-x86_64-3.8/deps/gsl/complex/math.o build/temp.linux-x86_64-3.8/deps/gsl/sys/infnan.o build/temp.linux-x86_64-3.8/deps/gsl/sys/fdiv.o build/temp.linux-x86_64-3.8/deps/gsl/sys/coerce.o build/temp.linux-x86_64-3.8/deps/gsl/err/stream.o -o build/lib.linux-x86_64-3.8/pypolyagamma/pypolyagamma.cpython-38-x86_64-linux-gnu.so
>     /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_2':
>     /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:46: multiple definition of `gsl_pow_2'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:46: first defined here
>     /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_3':
>     /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:47: multiple definition of `gsl_pow_3'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:47: first defined here
>     /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_4':
>     /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:48: multiple definition of `gsl_pow_4'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:48: first defined here
>     /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/cdf/gauss.o: in function `gsl_pow_5':
>     /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:49: multiple definition of `gsl_pow_5'; build/temp.linux-x86_64-3.8/deps/gsl/cdf/gamma.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_pow_int.h:49: first defined here
> ```
> 
> ending with
> 
> ```
> /home/zhangh9/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.8/deps/gsl/complex/math.o: in function `gsl_complex_rect':
>     /home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_complex_math.h:50: multiple definition of `gsl_complex_rect'; build/temp.linux-x86_64-3.8/deps/gsl/specfunc/psi.o:/home/zhangh9/st/pypolyagamma/deps/gsl/gsl/gsl_complex_math.h:50: first defined here
>     collect2: error: ld returned 1 exit status
>     error: command 'g++' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /home/zhangh9/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"'; __file__='"'"'/juno/home/zhangh9/st/pypolyagamma/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
> ```
> 
> We tried to change the `gslurl` in `setup.py` as mentioned in #18 but it didn't work either.

Sorry, I'm wondering whether you've fixed it? I meet the same problem too, thx!
