### ISSUE TITLE
issue with microsoft visual studio

### ISSUE THREAD

**Issue by mnouri62** [slinderman/pypolyagamma#9]
I'm trying to install pypolyagamma and I keep running into 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN
\\x86_amd64\\cl.exe' failed with exit status -1073741701

here is the full story:

(C:\Users\MN_WORK\Anaconda) C:\Users\MN_WORK>git clone git@github.com:slinderman
/pypolyagamma.git
Cloning into 'pypolyagamma'...
remote: Counting objects: 496, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 496 (delta 0), reused 0 (delta 0), pack-reused 492
Receiving objects: 100% (496/496), 886.15 KiB | 1.01 MiB/s, done.
Resolving deltas: 100% (280/280), done.
fatal: cannot create directory at 'aux': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

(C:\Users\MN_WORK\Anaconda) C:\Users\MN_WORK>cd pypolyagamma

(C:\Users\MN_WORK\Anaconda) C:\Users\MN_WORK\pypolyagamma>pip install pypolyagam
ma
Collecting pypolyagamma
  Using cached pypolyagamma-1.1.2.tar.gz
Requirement already satisfied: numpy in c:\users\mn_work\anaconda\lib\site-packa
ges (from pypolyagamma)
Requirement already satisfied: scipy in c:\users\mn_work\anaconda\lib\site-packa
ges (from pypolyagamma)
Requirement already satisfied: matplotlib in c:\users\mn_work\anaconda\lib\site-
packages (from pypolyagamma)
Requirement already satisfied: six>=1.10 in c:\users\mn_work\anaconda\lib\site-p
ackages (from matplotlib->pypolyagamma)
Requirement already satisfied: python-dateutil in c:\users\mn_work\anaconda\lib\
site-packages (from matplotlib->pypolyagamma)
Requirement already satisfied: pytz in c:\users\mn_work\anaconda\lib\site-packag
es (from matplotlib->pypolyagamma)
Requirement already satisfied: cycler>=0.10 in c:\users\mn_work\anaconda\lib\sit
e-packages (from matplotlib->pypolyagamma)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in c:\us
ers\mn_work\anaconda\lib\site-packages (from matplotlib->pypolyagamma)
Building wheels for collected packages: pypolyagamma
  Running setup.py bdist_wheel for pypolyagamma ... error
  Complete output from command C:\Users\MN_WORK\Anaconda\python.exe -u -c "impor
t setuptools, tokenize;__file__='C:\\Users\\MN_WORK\\AppData\\Local\\Temp\\pip-b
uild-lijygmkh\\pypolyagamma\\setup.py';f=getattr(tokenize, 'open', open)(__file_
_);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" bdist_wheel -d C:\Users\MN_WORK\AppData\Local\Temp\tmpwgk1a08upip-wheel-
 --python-tag cp36:
  '.' is not recognized as an internal or external command,
  operable program or batch file.
  'make' is not recognized as an internal or external command,
  operable program or batch file.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pypolyagamma
  copying pypolyagamma\distributions.py -> build\lib.win-amd64-3.6\pypolyagamma
  copying pypolyagamma\utils.py -> build\lib.win-amd64-3.6\pypolyagamma
  copying pypolyagamma\__init__.py -> build\lib.win-amd64-3.6\pypolyagamma
  running build_ext
  building 'pypolyagamma.pypolyagamma' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\pypolyagamma
  creating build\temp.win-amd64-3.6\Release\pypolyagamma\cpp
  creating build\temp.win-amd64-3.6\Release\pypolyagamma\cpp\include
  creating build\temp.win-amd64-3.6\Release\deps
  creating build\temp.win-amd64-3.6\Release\deps\gsl
  creating build\temp.win-amd64-3.6\Release\deps\gsl\rng
  creating build\temp.win-amd64-3.6\Release\deps\gsl\cdf
  creating build\temp.win-amd64-3.6\Release\deps\gsl\randist
  creating build\temp.win-amd64-3.6\Release\deps\gsl\err
  creating build\temp.win-amd64-3.6\Release\deps\gsl\specfunc
  creating build\temp.win-amd64-3.6\Release\deps\gsl\complex
  creating build\temp.win-amd64-3.6\Release\deps\gsl\sys
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c
 /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps/g
sl/gsl -IC:\Users\MN_WORK\Anaconda\lib\site-packages\numpy\core\include -IC:\Use
rs\MN_WORK\Anaconda\include -IC:\Users\MN_WORK\Anaconda\include "-IC:\Program Fi
les (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Win
dows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8
.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\
Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppypolyagamma/pypoly
agamma.cpp /Fobuild\temp.win-amd64-3.6\Release\pypolyagamma/pypolyagamma.obj -w
-DHAVE_INLINE
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN
\\x86_amd64\\cl.exe' failed with exit status -1073741701

  ----------------------------------------
  Failed building wheel for pypolyagamma
  Running setup.py clean for pypolyagamma
Failed to build pypolyagamma
Installing collected packages: pypolyagamma
  Running setup.py install for pypolyagamma ... error
    Complete output from command C:\Users\MN_WORK\Anaconda\python.exe -u -c "imp
ort setuptools, tokenize;__file__='C:\\Users\\MN_WORK\\AppData\\Local\\Temp\\pip
-build-lijygmkh\\pypolyagamma\\setup.py';f=getattr(tokenize, 'open', open)(__fil
e__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__,
'exec'))" install --record C:\Users\MN_WORK\AppData\Local\Temp\pip-yw_211xe-reco
rd\install-record.txt --single-version-externally-managed --compile:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    'make' is not recognized as an internal or external command,
    operable program or batch file.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pypolyagamma
    copying pypolyagamma\distributions.py -> build\lib.win-amd64-3.6\pypolyagamm
a
    copying pypolyagamma\utils.py -> build\lib.win-amd64-3.6\pypolyagamma
    copying pypolyagamma\__init__.py -> build\lib.win-amd64-3.6\pypolyagamma
    running build_ext
    building 'pypolyagamma.pypolyagamma' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\pypolyagamma
    creating build\temp.win-amd64-3.6\Release\pypolyagamma\cpp
    creating build\temp.win-amd64-3.6\Release\pypolyagamma\cpp\include
    creating build\temp.win-amd64-3.6\Release\deps
    creating build\temp.win-amd64-3.6\Release\deps\gsl
    creating build\temp.win-amd64-3.6\Release\deps\gsl\rng
    creating build\temp.win-amd64-3.6\Release\deps\gsl\cdf
    creating build\temp.win-amd64-3.6\Release\deps\gsl\randist
    creating build\temp.win-amd64-3.6\Release\deps\gsl\err
    creating build\temp.win-amd64-3.6\Release\deps\gsl\specfunc
    creating build\temp.win-amd64-3.6\Release\deps\gsl\complex
    creating build\temp.win-amd64-3.6\Release\deps\gsl\sys
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
/c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipypolyagamma/cpp/include -Ideps/gsl -Ideps
/gsl/gsl -IC:\Users\MN_WORK\Anaconda\lib\site-packages\numpy\core\include -IC:\U
sers\MN_WORK\Anaconda\include -IC:\Users\MN_WORK\Anaconda\include "-IC:\Program
Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\W
indows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits
\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC
:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppypolyagamma/pypo
lyagamma.cpp /Fobuild\temp.win-amd64-3.6\Release\pypolyagamma/pypolyagamma.obj -
w -DHAVE_INLINE
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status -1073741701

    ----------------------------------------
Command "C:\Users\MN_WORK\Anaconda\python.exe -u -c "import setuptools, tokenize
;__file__='C:\\Users\\MN_WORK\\AppData\\Local\\Temp\\pip-build-lijygmkh\\pypolya
gamma\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repla
ce('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --reco
rd C:\Users\MN_WORK\AppData\Local\Temp\pip-yw_211xe-record\install-record.txt --
single-version-externally-managed --compile" failed with error code 1 in C:\User
s\MN_WORK\AppData\Local\Temp\pip-build-lijygmkh\pypolyagamma\

(C:\Users\MN_WORK\Anaconda) C:\Users\MN_WORK\pypolyagamma>

**Comment by slinderman** [comment]
It looks like there are a few things going on here.  First of all, if you want to install from source you should run `pip install -e .` from the `pypolyagamma` directory.  Running `pip install pypolyagamma` will install from pypi.

More importantly,  I don't think this will work on Windows because `setup.py` tries to download, configure, and make GSL.  Unfortunately, GSL is a strict requirement of the code.  There might be some way to manually install it on Windows and then change the setup procedure to assume GSL is already present on the path, but this would be a significant change. 

Sorry for the trouble.

**Comment by slinderman** [comment]
I'm going to go ahead and close this as I don't see any way to support Windows.  Please feel free to reopen if you come up with a solution!
